global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: 'pipeline_metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'data_pipeline'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']