# # Data acquisition settings
# dataset:
#   name: "bigcode/the-stack-v2"
#   streaming: true
  
# languages:
#   - python
#   - java
#   - cpp
#   - javascript

# filters:
#   min_stars: 10
#   licenses:
#     - MIT
#     - Apache-2.0
#     - BSD-2-Clause
#     - BSD-3-Clause
#   min_file_size_bytes: 100
#   max_file_size_bytes: 1048576  # 1MB

# storage:
#   raw_data_path: "./data/raw/"
#   checkpoint_path: "./data/checkpoints/"
  
# download:
#   batch_size: 100
#   max_workers: 2
#   resume_from_checkpoint: true
# --------------------------------------------------------------------------


# Data Acquisition Configuration
# This file contains all settings for filtering and downloading code from The Stack v2

# Programming languages to download
languages:
  - Python
  - Java
  - C++
  - JavaScript

# Repository and file filtering criteria
filters:
  stars:
    min: 10                    # Minimum GitHub stars for repository
  
  file_size:
    min_bytes: 100             # Minimum file size (100 bytes)
    max_bytes: 1048576         # Maximum file size (1 MB)
  
  licenses:
    - mit
    - apache-2.0
    - bsd-2-clause
    - bsd-3-clause

# Output paths for downloaded code files
output_paths:
  base_dir: "data/code_files"
  python: "data/code_files/python"
  java: "data/code_files/java"
  cpp: "data/code_files/cpp"
  javascript: "data/code_files/javascript"

# Metadata storage paths
metadata_paths:
  base_dir: "data"
  python: "data/filtered_metadata_python.json"
  java: "data/filtered_metadata_java.json"
  cpp: "data/filtered_metadata_cpp.json"
  javascript: "data/filtered_metadata_javascript.json"

# AWS S3 Configuration
s3:
  bucket_name: "softwareheritage"
  content_prefix: "content/"
  
# Download settings
download:
  batch_size: 100              # Number of files to download per language
  encoding: "UTF-8"            # Default file encoding
  compression: "gzip"          # Compression format used in S3
  skip_existing: true          # Skip files that already exist locally

# Logging configuration
logging:
  level: "INFO"                # Log level: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "logs/data_acquisition.log"

# --------------------------------------------------------------------------

